### ISSUE TITLE
Image problems when remixing a project

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1576]
I've created a project, it is "published" and up to date:

* Editor - https://thimble.mozilla.org/en-US/user/flukeout/583154
* Published - https://thimbleprojects.org/flukeout/126424/

It contains two images
* whoa.gif
* whoa copy.gif

![image](https://cloud.githubusercontent.com/assets/25212/19978403/0e81940c-a1b4-11e6-8a39-d351dcd608ea.png)

When I remix it, only whoa.gif is there "whoa copy.gif" is gone...

![image](https://cloud.githubusercontent.com/assets/25212/19978416/19d374ce-a1b4-11e6-9452-47a294d5ca1a.png)

**Comment by flukeout** [comment]
Subsequently, I've removed both 
* whoa.gif
* whoa copy.gif
 
and "updated" the published version. When I remix it now, the Remix still contains ``whoa.gif``

cc @gideonthomas

**Comment by flukeout** [comment]
Was just following up from the problems we had during mozfest, seems like we are doing some strange things with images. Maybe they are not really being deleted, or somehow phantom-preserved and they come back during a remix?

**Comment by gideonthomas** [comment]
@flukeout can you confirm that this is not an issue if the filename contains no spaces? I think I remember there being a problem with filenames with spaces in them but I thought we fixed that so maybe this could be a regression.

**Comment by flukeout** [comment]
I renamed the file to whoa-copy.gif during that process and the error persisted. I'll try again from scratch but I'll make sure there are no spaces.

**Comment by flukeout** [comment]
So, it looks like, if...

* You publish a project with an image (or maybe other file)
* Delete that file
* Update the publish project
* Remix the published project
* **The file is back!**

File system of my original source project
![image](https://cloud.githubusercontent.com/assets/25212/19982755/95c0351c-a1c4-11e6-8efa-f5978ad6ad98.png)

File system of the remix
![image](https://cloud.githubusercontent.com/assets/25212/19982761/9cccfd40-a1c4-11e6-9f37-2e6c86a40c64.png)

**Comment by flukeout** [comment]
This second issue seems unrelated to the image that has a space in the filename problem.

**Comment by flukeout** [comment]
Whatever this seems old, closing until fresh NEW problems pop up!
