### ISSUE TITLE
Internal Fragment URL links don't work in the preview

### ISSUE THREAD

**Issue by SidneyNemzer** [mozilla/thimble.mozilla.org#2468]
### Description

A fragment link, such as `<a href="#heading">` does not correctly move the preview to the linked element. Instead, a 404 error page is shown.

![image of the error](https://user-images.githubusercontent.com/21203108/30087877-fd2fdbc4-9257-11e7-99bd-b6e53f0f90f2.png)

### Steps to Reproduce

1. Open a new project
2. Add an ID to an element in the `<body>`
3. Add an `<a>` that points to the id
4. Click the anchor in the preview

**Expected behavior:** The preview scrolls to the linked heading

**Actual behavior:** An error page is shown

(Sometimes the error page is delayed by a moment -- you may notice that the page DOES in fact scroll to the correct location)

### Versions

Reproduced on the latest Chrome and Firefox, Windows 10.

### Fix

I believe I've found a possible fix, as shown in this project (remix the project to view the demo in the thimble editor):
https://thimbleprojects.org/snemzer/311263/

**Comment by humphd** [comment]
That error usually means the service worker needs to be refreshed; although, it's possible that this bug (anchor links being broken in preview) is still around, though we thought we fixed it.  What happens if you close all but 1 instance of Thimble and refresh your browser vs. the preview?

**Comment by SidneyNemzer** [comment]
This has been happening to us for at least a month now. We've had the same issue on every thimble instance, across several computers (4 or 5, 2 PCs and a few Macbook Airs).

I've tried clearing all site data for thimble several times, but unfortunately it doesn't seem to make a difference.

**Comment by humphd** [comment]
When you say it's been happening for a while, do you mean specifically with anchor links, or with all pages in the preview?  I ask because some users report having a similar problem to yours with all pages, and refreshing the browser (and service worker we install) eventually fixes it.  However, you may be seeing something new; in which case I'll dig deeper into it.

**Comment by SidneyNemzer** [comment]
We're only having an issue when clicking an internal anchor link in the preview.

Thanks for looking into this, by the way!

**Comment by gideonthomas** [comment]
I think it might be by-passing our fragment-id checking code since we implemented cache storage.

**Comment by abdulhannanali** [comment]
This is infact a bug I am facing on Chrome v60 on Ubuntu 16.04. I also unregistered the service worker and installed the new service worker but the problem still persists. :)  Is this issue open for work?

**Comment by gideonthomas** [comment]
@abdulhannanali, this issue might be beyond the scope of a bug qualified for a new contributor. As such, @humphd has been assigned to work on this.
