### ISSUE TITLE
Preview box only displays an URL

### ISSUE THREAD

**Issue by jmortizruiz** [mozilla/thimble.mozilla.org#2611]
I'm trying to use thimble to teach 12 yo students some html. The problem is that the school computers (15 small Netbooks all alike) do not show the preview, but its url address.
I've tested some things:
I've tried to use thimble in Chromium or firefox, both in LINUX OS with the same result.
I've tried to use thimble in Google Chrome in Windows7 (computers have dual boot) same result.
I've tried in a different WiFi network (through my smartphone) and can't see the preview either.
I've tried to reload several times as indicated in a previous issue with no success.
I've cleared the browsers' cache and nothing.
I've tried with an external display and also nothing.
In the same network I'm able to use it in my computer perfectly (a regular size laptop), it seems to me then that the problem is in the student netbooks' hardware. I've realized that it takes quite long to load and the pages gives a warning message indicating this matter while loading.
I'm sending a couple of images with the netbooks model, the issue, and the screen resolution hoping that someone can help me.
![error chromium](https://user-images.githubusercontent.com/36565284/36341124-b6e300ba-13e9-11e8-86c6-64c0e0a7a652.png)
![error firefox](https://user-images.githubusercontent.com/36565284/36341125-b6fc93fe-13e9-11e8-80ea-7161fde0a76a.png)
![screen resolution](https://user-images.githubusercontent.com/36565284/36341126-b715761c-13e9-11e8-9d96-28806154d9e9.png)
![system](https://user-images.githubusercontent.com/36565284/36341127-b72de558-13e9-11e8-94f7-c5d5aec9c238.png)
![img_20180215_122328](https://user-images.githubusercontent.com/36565284/36341199-ef8b4930-13ea-11e8-9551-c2b71a954ef3.jpg)

**Comment by humphd** [comment]
This bug relates to third-party security settings in those browsers, and our Service Worker not registering properly.  We pushed a fix for this a while back, so I'm surprised to see this reported again; however, you should be able to force the preview to work by putting Thimble into a fallback mode: add `?cacheType=blob` to your URL and it should work.  Let me know.

**Comment by ryanwarsaw** [comment]
I had this issue happen to nearly half the machines when I did my Thimble session at MozFest, so this is definitely still an issue, I just don't know why.

**Comment by humphd** [comment]
The bug happens when a browser a) has support for service workers; and b) has a security/privacy setting enabled that blocks third-party scripts from accessing storage.  I wrote about it here, if you're interested http://blog.humphd.org/promise-to-catch/

We have two preview engines in Thimble: one uses service workers and cache storage, the other uses Blob URLs.  Where possible, we prefer to use service workers, but will (usually) automatically fallback to Blob URLs when we can't use storage.

@gideonthomas we shipped that fix for automatically falling back to blobs on prod, right?

**Comment by jmortizruiz** [comment]
It works, thank you a lot. The only thing is that 12 year old kids have to write it down manually in the url, but we'll deal with it. I'm sending a picture of the screen in case it helps someone else.
![_cachetype_blob](https://user-images.githubusercontent.com/36565284/36376479-860506ba-1573-11e8-94e9-b80cc6ab08fe.jpg)

Will we have an automatic option, or a fix for this in the future?

**Comment by humphd** [comment]
@jmortizruiz we do have an automatic option that should have solved this, so it's interesting that it isn't working for you.  I do note that you're using a localized version of Thimble--maybe our fallback code is broken with localized versions?

What happens if you try the same thing with the US English version?

Thanks for reporting this and helping us figure out what's wrong.  I'd like to fix this if I can.

**Comment by jmortizruiz** [comment]
I've already tried with the default english version, and it behaved the same way. I'll check tomorrow again when I've access to the computers, just in case. Let me know if there's somethin else I can do in the computers in order for you to have more and better information.

Thank you again for your help.

**Comment by humphd** [comment]
The only other thing that would be super helpful to me is to see what, if anything, is on the [browser's error console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console).  If there are any errors, having that text here would be great.

**Comment by jmortizruiz** [comment]
I've tried again with the default English (US) versión, with the same result.
Is this capture helpful?
![captura de pantalla de 2018-02-21 14-58-07](https://user-images.githubusercontent.com/36565284/36493839-ce103af6-1730-11e8-9562-4662f9b227eb.png)

**Comment by humphd** [comment]
@gideonthomas can you please confirm that we have shipped that auto-fallback fix on prod?

@jmortizruiz thanks, this is helpful to see

**Comment by gideonthomas** [comment]
Yeah we've definitely shipped it to prod: https://github.com/mozilla/brackets/commits/production
I wonder if it was a cache issue

**Comment by SteveDoesStuff** [comment]
Seeing the same thing today (also teaching kids) and the URL parameter is fixing it for us. While we haven't used Thimble on these laptops for at least a few months, since it's only showing up on some I think @gideonthomas may be right that it's cached an older version. Will try clearing cache on the laptops that are having issues at the end of our day to see if that solves it.

Thanks for the work-around though @humphd - really saved us from having a bunch of kids melting down!

**Comment by jmortizruiz** [comment]
I must say that I've realized today that this problem has been solved, and now it works perfect. Sorry for I don't know when it has actually started working ok ( I believe at least a week ago ).

Anyway, I just wanted to thak you guys for your time, patiente and good work.

**Comment by humphd** [comment]
@jmortizruiz glad it's working for you.  This particular bug is highly dependent on local conditions (cache, security settings, state of the service worker) and it's annoying to pinpoint.  Thanks for filing it, and helping us work through it with you.
